/* icons.js — 自由图标库(吴道子 · 与 motions.js 平级的「画面层」)
 *
 * AUTO-GENERATED by build_icons.mjs from Tabler Icons v3.44.0(MIT)。勿手改;改 MANIFEST 后重跑。
 * icon 独立于角色、漂浮在舞台、为强调关键词飞入(对标号的电池/时钟/箭头那一层);
 * 不是 rig-spec 的 prop/bubble(那是角色手持、跟着人走的)。
 * 契约:ICONS[id]={name,cat,keywords:[中文],enter,svg};Agent 只输出 icon id。
 */
(function () {
  const W = (inner) =>
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"' +
    ' stroke-linecap="round" stroke-linejoin="round">' + inner + '</svg>';

  const ICONS = {
    "clock": { name: "时钟", cat: "时间", enter: "pop", keywords: ["时间","来不及","紧迫","拖延","效率","赶时间"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0\" /><path d=\"M12 7v5l3 3\" />") },
    "hourglass": { name: "沙漏", cat: "时间", enter: "pop", keywords: ["等待","流逝","拖延","耗时间","熬"], svg: W("<path d=\"M6.5 7h11\" /><path d=\"M6.5 17h11\" /><path d=\"M6 20v-2a6 6 0 1 1 12 0v2a1 1 0 0 1 -1 1h-10a1 1 0 0 1 -1 -1\" /><path d=\"M6 4v2a6 6 0 1 0 12 0v-2a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1\" />") },
    "bolt": { name: "闪电", cat: "时间", enter: "pop", keywords: ["快","高效","爆发","立刻","瞬间","提速"], svg: W("<path d=\"M13 3l0 7l6 0l-8 11l0 -7l-6 0l8 -11\" />") },
    "calendar-event": { name: "日程", cat: "时间", enter: "pop", keywords: ["计划","日程","安排","deadline","排期"], svg: W("<path d=\"M4 7a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12\" /><path d=\"M16 3l0 4\" /><path d=\"M8 3l0 4\" /><path d=\"M4 11l16 0\" /><path d=\"M8 15h2v2h-2l0 -2\" />") },
    "battery-2": { name: "低电量", cat: "能量", enter: "pop", keywords: ["精力","内耗","累","耗尽","没电","疲惫"], svg: W("<path d=\"M6 7h11a2 2 0 0 1 2 2v.5a.5 .5 0 0 0 .5 .5a.5 .5 0 0 1 .5 .5v3a.5 .5 0 0 1 -.5 .5a.5 .5 0 0 0 -.5 .5v.5a2 2 0 0 1 -2 2h-11a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2\" /><path d=\"M7 10l0 4\" /><path d=\"M10 10l0 4\" />") },
    "flame": { name: "火焰", cat: "能量", enter: "rise", keywords: ["动力","热情","燃","爆","热度","冲劲"], svg: W("<path d=\"M12 10.941c2.333 -3.308 .167 -7.823 -1 -8.941c0 3.395 -2.235 5.299 -3.667 6.706c-1.43 1.408 -2.333 3.294 -2.333 5.588c0 3.704 3.134 6.706 7 6.706c3.866 0 7 -3.002 7 -6.706c0 -1.712 -1.232 -4.403 -2.333 -5.588c-2.084 3.353 -3.257 3.353 -4.667 2.235\" />") },
    "mood-sad": { name: "低落", cat: "能量", enter: "pop", keywords: ["难过","沮丧","焦虑","崩溃","情绪低"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M9 10l.01 0\" /><path d=\"M15 10l.01 0\" /><path d=\"M9.5 15.25a3.5 3.5 0 0 1 5 0\" />") },
    "mood-smile": { name: "开心", cat: "能量", enter: "pop", keywords: ["开心","轻松","满足","爽","舒服"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M9 10l.01 0\" /><path d=\"M15 10l.01 0\" /><path d=\"M9.5 15a3.5 3.5 0 0 0 5 0\" />") },
    "arrow-up": { name: "上升", cat: "趋势", enter: "rise", keywords: ["成长","提升","上涨","进步","变好"], svg: W("<path d=\"M12 5l0 14\" /><path d=\"M18 11l-6 -6\" /><path d=\"M6 11l6 -6\" />") },
    "arrow-down": { name: "下降", cat: "趋势", enter: "pop", keywords: ["下跌","衰退","退步","减少","变差"], svg: W("<path d=\"M12 5l0 14\" /><path d=\"M18 13l-6 6\" /><path d=\"M6 13l6 6\" />") },
    "trending-up": { name: "上升趋势", cat: "趋势", enter: "rise", keywords: ["增长","走高","复利","越来越好","曲线上扬"], svg: W("<path d=\"M3 17l6 -6l4 4l8 -8\" /><path d=\"M14 7l7 0l0 7\" />") },
    "trending-down": { name: "下降趋势", cat: "趋势", enter: "pop", keywords: ["下滑","走低","亏","下行","颓势"], svg: W("<path d=\"M3 7l6 6l4 -4l8 8\" /><path d=\"M21 10l0 7l-7 0\" />") },
    "rocket": { name: "火箭", cat: "趋势", enter: "rise", keywords: ["起飞","突破","爆发增长","逆袭","快速成长"], svg: W("<path d=\"M4 13a8 8 0 0 1 7 7a6 6 0 0 0 3 -5a9 9 0 0 0 6 -8a3 3 0 0 0 -3 -3a9 9 0 0 0 -8 6a6 6 0 0 0 -5 3\" /><path d=\"M7 14a6 6 0 0 0 -3 6a6 6 0 0 0 6 -3\" /><path d=\"M14 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />") },
    "chart-line": { name: "增长曲线", cat: "趋势", enter: "rise", keywords: ["数据","增长","复盘","业绩","曲线"], svg: W("<path d=\"M4 19l16 0\" /><path d=\"M4 15l4 -6l4 2l4 -5l4 4\" />") },
    "stairs-up": { name: "进阶", cat: "趋势", enter: "rise", keywords: ["台阶","进阶","一步步","升级","层层"], svg: W("<path d=\"M22 6h-5v5h-5v5h-5v5h-5\" /><path d=\"M6 10v-7\" /><path d=\"M3 6l3 -3l3 3\" />") },
    "bulb": { name: "灯泡", cat: "认知", enter: "pop", keywords: ["灵感","顿悟","想法","点子","开窍","明白"], svg: W("<path d=\"M3 12h1m8 -9v1m8 8h1m-15.4 -6.4l.7 .7m12.1 -.7l-.7 .7\" /><path d=\"M9 16a5 5 0 1 1 6 0a3.5 3.5 0 0 0 -1 3a2 2 0 0 1 -4 0a3.5 3.5 0 0 0 -1 -3\" /><path d=\"M9.7 17l4.6 0\" />") },
    "brain": { name: "大脑", cat: "认知", enter: "pop", keywords: ["认知","思维","想太多","脑子","理性","心智"], svg: W("<path d=\"M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8\" /><path d=\"M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8\" /><path d=\"M17.5 16a3.5 3.5 0 0 0 0 -7h-.5\" /><path d=\"M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0\" /><path d=\"M6.5 16a3.5 3.5 0 0 1 0 -7h.5\" /><path d=\"M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10\" />") },
    "eye": { name: "眼睛", cat: "认知", enter: "draw", keywords: ["看见","洞察","被看见","观察","关注","发现"], svg: W("<path d=\"M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" /><path d=\"M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6\" />") },
    "puzzle": { name: "拼图", cat: "认知", enter: "pop", keywords: ["想通","解决","关键一块","拼上","逻辑"], svg: W("<path d=\"M4 7h3a1 1 0 0 0 1 -1v-1a2 2 0 0 1 4 0v1a1 1 0 0 0 1 1h3a1 1 0 0 1 1 1v3a1 1 0 0 0 1 1h1a2 2 0 0 1 0 4h-1a1 1 0 0 0 -1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-1a2 2 0 0 0 -4 0v1a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1h1a2 2 0 0 0 0 -4h-1a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1\" />") },
    "book": { name: "书", cat: "认知", enter: "pop", keywords: ["学习","知识","读书","方法论","原理"], svg: W("<path d=\"M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0\" /><path d=\"M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0\" /><path d=\"M3 6l0 13\" /><path d=\"M12 6l0 13\" /><path d=\"M21 6l0 13\" />") },
    "bookmark": { name: "书签", cat: "认知", enter: "pop", keywords: ["记住","收藏","重点","标记","划重点"], svg: W("<path d=\"M18 7v14l-6 -4l-6 4v-14a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4\" />") },
    "magnet": { name: "磁铁", cat: "认知", enter: "pop", keywords: ["吸引","聚焦","抓住","磁场","注意力"], svg: W("<path d=\"M4 13v-8a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v8a2 2 0 0 0 6 0v-8a2 2 0 0 1 2 -2h1a2 2 0 0 1 2 2v8a8 8 0 0 1 -16 0\" /><path d=\"M4 8l5 0\" /><path d=\"M15 8l4 0\" />") },
    "zoom-in": { name: "放大镜", cat: "认知", enter: "pop", keywords: ["看清","深究","细节","深挖","聚焦"], svg: W("<path d=\"M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0\" /><path d=\"M7 10l6 0\" /><path d=\"M10 7l0 6\" /><path d=\"M21 21l-6 -6\" />") },
    "check": { name: "对勾", cat: "判断", enter: "draw", keywords: ["正确","认同","该这样","搞定","完成","没问题"], svg: W("<path d=\"M5 12l5 5l10 -10\" />") },
    "x": { name: "红叉", cat: "判断", enter: "pop", keywords: ["错误","否定","别这样","不对","禁止","失败"], svg: W("<path d=\"M18 6l-12 12\" /><path d=\"M6 6l12 12\" />") },
    "alert-triangle": { name: "警告", cat: "判断", enter: "pop", keywords: ["警惕","注意","坑","危险","小心","风险"], svg: W("<path d=\"M12 9v4\" /><path d=\"M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0\" /><path d=\"M12 16h.01\" />") },
    "alert-circle": { name: "提醒", cat: "判断", enter: "pop", keywords: ["注意","提醒","留意","重点","别忽略"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0\" /><path d=\"M12 8v4\" /><path d=\"M12 16h.01\" />") },
    "ban": { name: "禁止", cat: "判断", enter: "pop", keywords: ["别","不要","禁止","杜绝","停止","戒"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M5.7 5.7l12.6 12.6\" />") },
    "thumb-up": { name: "点赞", cat: "判断", enter: "pop", keywords: ["赞同","好","认可","支持","推荐"], svg: W("<path d=\"M7 11v8a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-7a1 1 0 0 1 1 -1h3a4 4 0 0 0 4 -4v-1a2 2 0 0 1 4 0v5h3a2 2 0 0 1 2 2l-1 5a2 3 0 0 1 -2 2h-7a3 3 0 0 1 -3 -3\" />") },
    "thumb-down": { name: "反对", cat: "判断", enter: "pop", keywords: ["反对","差","不行","否决","踩"], svg: W("<path d=\"M7 13v-8a1 1 0 0 0 -1 -1h-2a1 1 0 0 0 -1 1v7a1 1 0 0 0 1 1h3a4 4 0 0 1 4 4v1a2 2 0 0 0 4 0v-5h3a2 2 0 0 0 2 -2l-1 -5a2 3 0 0 0 -2 -2h-7a3 3 0 0 0 -3 3\" />") },
    "shield": { name: "盾牌", cat: "判断", enter: "pop", keywords: ["保护","防御","安全","底线","边界"], svg: W("<path d=\"M12 3a12 12 0 0 0 8.5 3a12 12 0 0 1 -8.5 15a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3\" />") },
    "question-mark": { name: "问号", cat: "判断", enter: "pop", keywords: ["疑问","反问","为什么","真的吗","凭什么"], svg: W("<path d=\"M8 8a3.5 3 0 0 1 3.5 -3h1a3.5 3 0 0 1 3.5 3a3 3 0 0 1 -2 3a3 4 0 0 0 -2 4\" /><path d=\"M12 19l0 .01\" />") },
    "target": { name: "靶心", cat: "目标", enter: "pop", keywords: ["目标","聚焦","精准","重点","命中","方向"], svg: W("<path d=\"M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /><path d=\"M7 12a5 5 0 1 0 10 0a5 5 0 1 0 -10 0\" /><path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" />") },
    "flag": { name: "旗帜", cat: "目标", enter: "rise", keywords: ["里程碑","目标达成","小目标","插旗","阶段"], svg: W("<path d=\"M5 5a5 5 0 0 1 7 0a5 5 0 0 0 7 0v9a5 5 0 0 1 -7 0a5 5 0 0 0 -7 0v-9\" /><path d=\"M5 21v-7\" />") },
    "trophy": { name: "奖杯", cat: "目标", enter: "rise", keywords: ["成就","赢","冠军","成功","拿下"], svg: W("<path d=\"M8 21l8 0\" /><path d=\"M12 17l0 4\" /><path d=\"M7 4l10 0\" /><path d=\"M17 4v8a5 5 0 0 1 -10 0v-8\" /><path d=\"M3 9a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" /><path d=\"M17 9a2 2 0 1 0 4 0a2 2 0 1 0 -4 0\" />") },
    "medal": { name: "奖牌", cat: "目标", enter: "rise", keywords: ["荣誉","认可","名次","上榜","获奖"], svg: W("<path d=\"M12 4v3m-4 -3v6m8 -6v6\" /><path d=\"M12 18.5l-3 1.5l.5 -3.5l-2 -2l3 -.5l1.5 -3l1.5 3l3 .5l-2 2l.5 3.5l-3 -1.5\" />") },
    "crown": { name: "王冠", cat: "目标", enter: "rise", keywords: ["第一","顶尖","王者","头部","领先"], svg: W("<path d=\"M12 6l4 6l5 -4l-2 10h-14l-2 -10l5 4l4 -6\" />") },
    "star": { name: "星", cat: "目标", enter: "pop", keywords: ["重点","高光","优秀","加分","关键","亮点"], svg: W("<path d=\"M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873l-6.158 -3.245\" />") },
    "mountain": { name: "高山", cat: "目标", enter: "rise", keywords: ["挑战","难关","攀登","大目标","高峰"], svg: W("<path d=\"M3 20h18l-6.921 -14.612a2.3 2.3 0 0 0 -4.158 0l-6.921 14.612\" /><path d=\"M7.5 11l2 2.5l2.5 -2.5l2 3l2.5 -2\" />") },
    "currency-yen": { name: "钱", cat: "价值", enter: "pop", keywords: ["钱","收入","价值","工资","涨薪","回报"], svg: W("<path d=\"M12 19v-7l-5 -7m10 0l-5 7\" /><path d=\"M8 17l8 0\" /><path d=\"M8 13l8 0\" />") },
    "coin": { name: "硬币", cat: "价值", enter: "pop", keywords: ["赚钱","积累","本钱","收益","一分一毫"], svg: W("<path d=\"M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\" /><path d=\"M14.8 9a2 2 0 0 0 -1.8 -1h-2a2 2 0 1 0 0 4h2a2 2 0 1 1 0 4h-2a2 2 0 0 1 -1.8 -1\" /><path d=\"M12 7v10\" />") },
    "gift": { name: "礼物", cat: "价值", enter: "pop", keywords: ["回报","红利","惊喜","福利","给予"], svg: W("<path d=\"M3 9a1 1 0 0 1 1 -1h16a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-16a1 1 0 0 1 -1 -1l0 -2\" /><path d=\"M12 8l0 13\" /><path d=\"M19 12v7a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-7\" /><path d=\"M7.5 8a2.5 2.5 0 0 1 0 -5a4.8 8 0 0 1 4.5 5a4.8 8 0 0 1 4.5 -5a2.5 2.5 0 0 1 0 5\" />") },
    "diamond": { name: "钻石", cat: "价值", enter: "pop", keywords: ["价值","稀缺","高价值","硬通货","珍贵"], svg: W("<path d=\"M6 5h12l3 5l-8.5 9.5a.7 .7 0 0 1 -1 0l-8.5 -9.5l3 -5\" /><path d=\"M10 12l-2 -2.2l.6 -1\" />") },
    "message-circle": { name: "对话气泡", cat: "沟通", enter: "rise", keywords: ["沟通","话术","回应","反击","表达","回怼"], svg: W("<path d=\"M3 20l1.3 -3.9c-2.324 -3.437 -1.426 -7.872 2.1 -10.374c3.526 -2.501 8.59 -2.296 11.845 .48c3.255 2.777 3.695 7.266 1.029 10.501c-2.666 3.235 -7.615 4.215 -11.574 2.293l-4.7 1\" />") },
    "users": { name: "人群", cat: "沟通", enter: "pop", keywords: ["社交","团队","人脉","关系","大家","群体"], svg: W("<path d=\"M5 7a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\" /><path d=\"M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2\" /><path d=\"M16 3.13a4 4 0 0 1 0 7.75\" /><path d=\"M21 21v-2a4 4 0 0 0 -3 -3.85\" />") },
    "heart": { name: "心", cat: "沟通", enter: "pop", keywords: ["情绪","在意","关系","喜欢","用心","感受"], svg: W("<path d=\"M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572\" />") },
    "speakerphone": { name: "喇叭", cat: "沟通", enter: "pop", keywords: ["宣传","喊话","发声","表态","主张","announce"], svg: W("<path d=\"M18 8a3 3 0 0 1 0 6\" /><path d=\"M10 8v11a1 1 0 0 1 -1 1h-1a1 1 0 0 1 -1 -1v-5\" /><path d=\"M12 8l4.524 -3.77a.9 .9 0 0 1 1.476 .692v12.156a.9 .9 0 0 1 -1.476 .692l-4.524 -3.77h-8a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h8\" />") },
    "lock": { name: "锁", cat: "突破", enter: "pop", keywords: ["受限","卡住","锁死","困住","限制","封闭"], svg: W("<path d=\"M5 13a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6\" /><path d=\"M11 16a1 1 0 1 0 2 0a1 1 0 0 0 -2 0\" /><path d=\"M8 11v-4a4 4 0 1 1 8 0v4\" />") },
    "key": { name: "钥匙", cat: "突破", enter: "pop", keywords: ["解法","关键","突破口","答案","钥匙","破局"], svg: W("<path d=\"M16.555 3.843l3.602 3.602a2.877 2.877 0 0 1 0 4.069l-2.643 2.643a2.877 2.877 0 0 1 -4.069 0l-.301 -.301l-6.558 6.558a2 2 0 0 1 -1.239 .578l-.175 .008h-1.172a1 1 0 0 1 -.993 -.883l-.007 -.117v-1.172a2 2 0 0 1 .467 -1.284l.119 -.13l.414 -.414h2v-2h2v-2l2.144 -2.144l-.301 -.301a2.877 2.877 0 0 1 0 -4.069l2.643 -2.643a2.877 2.877 0 0 1 4.069 0\" /><path d=\"M15 9h.01\" />") },
    "door": { name: "门", cat: "突破", enter: "pop", keywords: ["机会","出口","入口","选择","一扇门"], svg: W("<path d=\"M14 12v.01\" /><path d=\"M3 21h18\" /><path d=\"M6 21v-16a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v16\" />") },
    "bomb": { name: "炸弹", cat: "突破", enter: "pop", keywords: ["危机","踩坑","雷","隐患","爆雷","风险"], svg: W("<path d=\"M15.349 5.349l3.301 3.301a1.2 1.2 0 0 1 0 1.698l-.972 .972a7.5 7.5 0 1 1 -5 -5l.972 -.972a1.2 1.2 0 0 1 1.698 0l.001 .001\" /><path d=\"M17 7l1.293 -1.293a2.414 2.414 0 0 0 .707 -1.707a1 1 0 0 1 1 -1h1\" /><path d=\"M7 13a3 3 0 0 1 3 -3\" />") },
    "tool": { name: "工具", cat: "工具", enter: "pop", keywords: ["工具","方法","手段","招式","套路"], svg: W("<path d=\"M7 10h3v-3l-3.5 -3.5a6 6 0 0 1 8 8l6 6a2 2 0 0 1 -3 3l-6 -6a6 6 0 0 1 -8 -8l3.5 3.5\" />") },
    "settings": { name: "齿轮", cat: "工具", enter: "pop", keywords: ["机制","系统","底层逻辑","原理","运转"], svg: W("<path d=\"M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065\" /><path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" />") },
    "route": { name: "路线", cat: "工具", enter: "draw", keywords: ["路径","方法","步骤","路线图","怎么走"], svg: W("<path d=\"M3 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0\" /><path d=\"M19 7a2 2 0 1 0 0 -4a2 2 0 0 0 0 4\" /><path d=\"M11 19h5.5a3.5 3.5 0 0 0 0 -7h-8a3.5 3.5 0 0 1 0 -7h4.5\" />") },
  };

  const ENTERS = {
    pop: { name: '弹入',
      keyframes: [
        { transform: 'scale(0.2)', opacity: 0, offset: 0 },
        { transform: 'scale(1.12)', opacity: 1, offset: 0.7 },
        { transform: 'scale(1)', opacity: 1, offset: 1 },
      ],
      options: { duration: 420, easing: 'cubic-bezier(.34,1.56,.64,1)', fill: 'both' } },
    rise: { name: '上浮',
      keyframes: [
        { transform: 'translateY(24px)', opacity: 0 },
        { transform: 'translateY(0px)', opacity: 1 },
      ],
      options: { duration: 460, easing: 'cubic-bezier(.2,.8,.3,1)', fill: 'both' } },
    // draw:真正的描边「手画」由 player 给 path 设 pathLength + stroke-dashoffset 驱动;此处淡入兜底。
    draw: { name: '描边手画',
      keyframes: [{ opacity: 0 }, { opacity: 1 }],
      options: { duration: 600, easing: 'ease-out', fill: 'both' } },
  };

  window.RIG_ICONS = ICONS;
  window.RIG_ICON_ENTERS = ENTERS;
  window.RIG_ICON_LIST = Object.keys(ICONS).map((id) => ({ id, ...ICONS[id] }));
})();
